# Generated by Django 3.2.7 on 2021-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('NotActive/Confirm', 'NotActive/Confirm'), ('NotActive/Reject', 'NotActive/Reject'), ('Review', 'Review')], default='Active', max_length=100),
        ),
    ]
