# Generated by Django 3.2.7 on 2021-09-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_comment',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
