# Generated by Django 3.2.7 on 2021-09-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_comment_last_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_comment',
            field=models.BooleanField(default=False),
        ),
    ]
