# Generated by Django 3.2.7 on 2021-09-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_temporarytokenmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytokenmodel',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
