# Generated by Django 3.2.7 on 2021-09-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_temporarytokenmodel_last_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='WishList',
        ),
    ]
